training:
  batch_size: 512  # 2048
  n_epochs: 100  # 200
  n_iters: 80001
  snapshot_freq: 5000
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: false

sampling:
  batch_size: 1
  data_init: false
  step_lr: 0.001  # 0.0000009
  n_steps_each: 3
  ckpt_id: 80000
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 8

fast_fid:
  batch_size: 1000
  num_samples: 1000
  step_lr: 0.0000009
  n_steps_each: 3
  begin_ckpt: 100000
  end_ckpt: 80000
  verbose: false
  ensemble: false

test:
  begin_ckpt: 5000
  end_ckpt: 80000
  batch_size: 100

data:
  dataset: "CINE127"
  image_size: 32  # T = 25
  channels: 64  # 4
  th: 0.015  # norm(x) / x.numel()
  leq: 13.97  # leq : gt = 13.97 : 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 8

model:
  sigma_begin: 40  # 10
  num_classes: 200  # 100
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.001

recons:
  sigma_dist: geometric
  sigma_begin: 40
  num_classes: 400
  sigma_end: 0.01
  