Seg:
  spatial_dims: 2
  in_channels: 1
  out_channels: 2
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]

Clf:
  in_channels: 1
  num_cls: 10
  resnet_name: "resnet18"
  pretrained: false
